name: deploy main to firebase

on:
  workflow_run:
    workflows: ["test_and_build"]
    branches: [main]
    types:
      - completed
jobs:
  test_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: download build artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: build
      - name: deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_USER_RECORDS_APP }}'
          channelId: live
          projectId: user-records-app
